name: C/C++ CI

on:
  push:
    branches:
      - main
      - autograder
  pull_request:
    branches:
      - main
      - autograder

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
